import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        "on-background": "#1a1a1a",
        foreground: "#1a1a1a",
        primary: "#d4a520",
        "primary-container": "#f0e68c",
        "primary-fixed": "#fef8e0",
        "primary-fixed-dim": "#e8d773",
        "primary-foreground": "#ffffff",
        "inverse-primary": "#e8c93d",
        secondary: "#757070",
        "secondary-container": "#e8e3dd",
        "secondary-fixed": "#f2ebe5",
        "secondary-fixed-dim": "#dcd4cc",
        tertiary: "#8a8077",
        "tertiary-container": "#e8dace",
        "tertiary-fixed": "#f6ebe0",
        "tertiary-fixed-dim": "#e0cdb3",
        error: "#c5392d",
        "error-container": "#fde7e3",
        surface: "#ffffff",
        "surface-dim": "#e0dcd8",
        "surface-bright": "#ffffff",
        "surface-light": "#ffffff",
        "surface-alt": "#f5f5f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f9f7",
        "surface-container": "#f5f5f0",
        "surface-container-high": "#efefeb",
        "surface-container-highest": "#e8e3dd",
        "surface-variant": "#f0ebe5",
        "surface-tint": "#d4a520",
        "inverse-surface": "#1a1a1a",
        "inverse-on-surface": "#f5f1ed",
        "on-surface": "#1a1a1a",
        "on-surface-variant": "#6b7280",
        "on-primary": "#ffffff",
        "on-primary-container": "#5a4200",
        "on-primary-fixed": "#3a2a00",
        "on-primary-fixed-variant": "#7d5f00",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#747070",
        "on-secondary-fixed": "#2d2d29",
        "on-secondary-fixed-variant": "#605b55",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#6e6456",
        "on-tertiary-fixed": "#3a3026",
        "on-tertiary-fixed-variant": "#7f6f5e",
        "on-error": "#ffffff",
        "on-error-container": "#a32820",
        accent: "#f0e68c",
        "accent-foreground": "#3d3a30",
        destructive: "#c5392d",
        "destructive-foreground": "#ffffff",
        ring: "#e0c87f",
        muted: "#e8e2da",
        "muted-foreground": "#6b7280",
        outline: "#9d938a",
        "outline-variant": "#e0e0e0",
        sidebar: "#1a1a1a",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "Segoe UI", "system-ui", "sans-serif"],
        display: ["var(--font-sora)", "var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.85rem",
        xl: "1.2rem",
        full: "9999px",
      },
      spacing: {
        "xs": "0.5rem",
        "sm": "1rem",
        "md": "1.5rem",
        "lg": "2rem",
        "xl": "3rem",
        "2xl": "4rem",
      },
    },
  },
  plugins: [],
};

export default config;
